package syntaxanalyzer;

public enum NodeType {
    SIGNAL_PROGRAM,
    PROGRAM,
    PROCEDURE_IDENTIFIER,
    BLOCK,
    DECLARATIONS,
    STATEMENTS_LIST,
    LABEL_DECLARATIONS,
    LABELS_LIST,
    UNSIGNED_INTEGER,
    STATEMENT,
    CONDITION_STATEMENT,
    INCOMPLETE_CONDITION_STATEMENT,
    ALTERNATIVE_PART,
    CONDITIONAL_EXPRESSION,
    VARIABLE_IDENTIFIER,
    IDENTIFIER,
    LEXEM,
    EMPTY
}
